# Setup
title: ABC Dataset
tagline: A Big CAD Model Dataset For Geometric Deep Learning
baseurl:      ""
paginate: 1
locale: "en"

# About/contact
author:
  name:       Sebastian Koch
  url:        https://deep-geometry.github.io/abc-dataset/

# Gems
gems:
  - jekyll-paginate
